export const TESTIMONIAL_CASE_LINKS: Record<string, string> = {
  "Юлия": "/blog/smm-dlya-b2b-proizvodstva",
  Yulia: "/blog/smm-dlya-b2b-proizvodstva",
  "Fancy decor": "/blog/smm-dlya-b2b-proizvodstva",
  "Максим": "/blog/keis-pinterest-studia-dizaina",
  Maxim: "/blog/keis-pinterest-studia-dizaina",
  "BELOUSOV STUDIO": "/blog/keis-pinterest-studia-dizaina",
  "Елена и Георгий": "/blog/keis-prodvizhenie-premium-turov",
  "Elena & Georgiy": "/blog/keis-prodvizhenie-premium-turov",
  "Travel Times": "/blog/keis-prodvizhenie-premium-turov",
  "Антон": "/blog/2keis-premium-kurort-horeca",
  Anton: "/blog/2keis-premium-kurort-horeca",
  "Connected show": "/blog/2keis-premium-kurort-horeca",
  "Наталья": "/blog/2keis-premium-kurort-horeca",
  Natalia: "/blog/2keis-premium-kurort-horeca",
  "Altay village": "/blog/2keis-premium-kurort-horeca",
  "Анастасия": "/blog/keis-smm-shou-improvizacii",
  Anastasia: "/blog/keis-smm-shou-improvizacii",
};
